# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Vuexo
subtitle: "A SPA blog theme for Hexo, built with Vue.js"
description: "Vuexo is a modern, single-page application (SPA) blog theme for Hexo, designed to provide a seamless and interactive user experience. It leverages the power of Vue.js to deliver dynamic content and smooth navigation, making it an ideal choice for developers and bloggers who want a fast and responsive site. With its clean design and customizable features, Vuexo enhances the blogging experience while maintaining the simplicity and efficiency of Hexo. Whether you're sharing articles, tutorials, or personal stories, Vuexo offers a robust platform to showcase your content effectively."
keywords: "Vue.js, Hexo, SPA, blog theme, modern design, interactive user experience, dynamic content, fast site, responsive design, customizable features"
author: lichenghsu
language: zh-TW
locale: zh-TW
copyright: "Copyright © 2025 lichenghsu"
timezone: "Asia/Taipei"

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://lcxlab.com 
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false # Enable post asset folder 
relative_link: false
future: true
marked:
  prependRoot: true
  postAsset: true

syntax_highlighter: prismjs
highlight:
  enable: false
  hljs: false
  line_number: false
prism_plugin:
  enable: false

index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: 
  - "*.md"
  - "*.html"
  - "README.md"
  - "README.zh-TW.md"
  - "README.en.md"
  - "README.ja.md"
  - "README.zh-CN.md"
  - "README.fr.md"
  - "README.es.md"
  - "README.de.md"
  - "README.ru.md"
  - "README.it.md"
  - "README.pt-BR.md"
exclude: 
  - "node_modules"
  - "db.json"
  - "package.json"
  - "package-lock.json"
  - "yarn.lock"
  - "public"
  - ".gitignore"
  - ".editorconfig"
  - ".eslintrc.js"
  - ".prettierrc.js"
  - ".babelrc"

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: vuexo

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/lichenghsu/lcxlab.github.io.git
  branch: gh-pages

# JsonContent

jsonContent:
  file: content.json
  meta: false
  posts:
    title: true
    slug: true
    date: true
    content: true
    excerpt: true
    cover: true
    categories: true
    tags: true
    layout: true
    published: true
    sticky: true
  pages:
    title: true
    slug: true
    date: true
    content: true
    layout: true
    published: true
