name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - origin main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build Hexo site with Tailwind
        run: |
          npm run build:css
          npx hexo clean
          npx hexo generate

      - name: Write CNAME
        run: echo "lcxlab.com" > public/CNAME

      - name: Add .nojekyll (to prevent GitHub ignoring _ dirs)
        run: echo "" > public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages